### ISSUE TITLE
lien vers un nouvel onglet

### ISSUE THREAD

**Issue by StephaneThomin** [Youssef51/oumanger#9]
target_blank pour ne pas sortir du site quand on ouvre un lien

**Comment by wasthishelpful** [comment]
attention à n'ouvrir des onglets que si c'est justifié. quelques mauvaises raisons d'ouvrir un autre onglet quand on clique sur un lien :

https://css-tricks.com/use-target_blank/

il y a aussi des bonnes raisons dans la liste ;)

**Comment by Youssef51** [comment]
L'idée générale est de laisser l'utilisateur choisir d'ouvrir un nouvel onglet.
